/* AUTO-GENERATED by build-styles.js — 編集は css/preview.css を行い再生成してください */
(function () {
  'use strict';
  const LP = (window.LP = window.LP || {});
  // LP 本体CSS文字列（プレビュー/エクスポートで共用）
  LP.LP_CSS = `/* =========================================================
   preview.css — LP 本体スタイル（エディタプレビュー ＆ エクスポートHTML で共用）
   テーマ色は CSS 変数で注入:
   --lp-primary --lp-accent --lp-bg --lp-text --lp-radius --lp-font
   ========================================================= */

.lp-root {
  /* デフォルト（上書き前提） */
  --lp-primary: #e87a8b;
  --lp-accent: #f6c453;
  --lp-bg: #ffffff;
  --lp-text: #2d2a26;
  --lp-radius: 12px;
  --lp-font: 'Hiragino Sans','Hiragino Kaku Gothic ProN','Noto Sans JP',sans-serif;
  --lp-muted: #8a8580;
  --lp-line: #eceae6;
  --lp-soft: #f6f4f0;
}

.lp-root, .lp-root * {
  box-sizing: border-box;
}
.lp-root {
  font-family: var(--lp-font);
  color: var(--lp-text);
  background: var(--lp-bg);
  line-height: 1.75;
  font-size: 15px;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  margin: 0;
}
.lp-root p, .lp-root h1, .lp-root h2, .lp-root h3, .lp-root ul, .lp-root figure { margin: 0; }
.lp-root img { max-width: 100%; height: auto; display: block; }
.lp-root a { color: var(--lp-primary); text-decoration: none; }

/* レイアウト コンテナ */
.lp-container { max-width: 1120px; margin: 0 auto; padding: 0 20px; }
.lp-narrow { max-width: 820px; }
.lp-center { text-align: center; }

/* セクション間隔 */
.lp-root > section { padding: 56px 0; }

/* 見出し */
.lp-eyebrow {
  display: inline-block; font-size: 13px; font-weight: 700;
  letter-spacing: .14em; color: var(--lp-primary);
  background: color-mix(in srgb, var(--lp-primary) 12%, transparent);
  padding: 4px 14px; border-radius: 30px; margin-bottom: 16px;
}
.lp-h2 {
  font-size: clamp(22px, 4vw, 32px); font-weight: 800; line-height: 1.4;
  margin-bottom: 28px;
}
.lp-section-head { margin-bottom: 36px; }
.lp-section-head.lp-center .lp-h2 { margin-bottom: 16px; }

/* ボタン */
.lp-btn {
  display: inline-block; padding: 14px 32px; border-radius: var(--lp-radius);
  font-weight: 700; font-size: 16px; cursor: pointer; border: 2px solid transparent;
  transition: transform .15s ease, box-shadow .15s ease, opacity .15s;
  text-align: center; line-height: 1.3;
}
.lp-btn:hover { transform: translateY(-2px); }
.lp-btn:active { transform: translateY(0); }
.lp-btn-primary { background: var(--lp-primary); color: #fff; box-shadow: 0 6px 18px color-mix(in srgb, var(--lp-primary) 40%, transparent); }
.lp-btn-outline { background: transparent; border-color: var(--lp-primary); color: var(--lp-primary); }
.lp-btn-white { background: #fff; color: var(--lp-text); box-shadow: 0 6px 18px rgba(0,0,0,.18); }
.lp-btn-lg { padding: 18px 44px; font-size: 18px; }
.lp-btn-block { display: block; width: 100%; }

/* ============ お知らせバー ============ */
.lp-notice {
  padding: 10px 16px; text-align: center; font-size: 13px; font-weight: 600;
  letter-spacing: .02em;
}
.lp-notice a { color: inherit; display: block; }
.lp-notice .nt-link { margin-left: 8px; opacity: .9; }

/* ============ ヒーロー ============ */
.lp-hero {
  background-size: cover; background-position: center; color: #fff;
  display: flex; align-items: center; padding: 60px 0;
}
.lp-hero-inner { max-width: 720px; }
.lp-align-center { margin-left: auto; margin-right: auto; }
.lp-align-right { margin-left: auto; }
.lp-hero .lp-eyebrow { background: rgba(255,255,255,.2); color: #fff; }
.lp-hero-title {
  font-size: clamp(28px, 5.5vw, 46px); font-weight: 800; line-height: 1.35;
  margin: 6px 0 18px; text-shadow: 0 2px 12px rgba(0,0,0,.25);
}
.lp-hero-sub { font-size: clamp(15px, 2.2vw, 18px); margin-bottom: 28px; opacity: .98; }
.lp-hero-cta { margin-bottom: 12px; }
.lp-hero-note { font-size: 13px; opacity: .92; }

/* ============ リード文 ============ */
.lp-lead { padding: 64px 0; }
.lp-lead .lp-h2 { margin-bottom: 22px; }
.lp-lead-body { font-size: 16px; max-width: 680px; margin: 0 auto; }

/* ============ 3つのメリット ============ */
.lp-feature-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 24px; }
.lp-feature {
  background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius);
  padding: 28px 22px; text-align: center;
  box-shadow: 0 2px 8px rgba(0,0,0,.03);
}
.lp-feature-icon { font-size: 42px; line-height: 1; margin-bottom: 12px; }
.lp-feature-title { font-size: 18px; font-weight: 700; margin-bottom: 8px; }
.lp-feature-desc { font-size: 14px; color: var(--lp-muted); }

/* ============ 画像＋文章 ============ */
.lp-it-row {
  display: grid; grid-template-columns: 1fr 1fr; gap: 36px; align-items: center;
  margin-bottom: 56px;
}
.lp-it-row:last-child { margin-bottom: 0; }
.lp-it-reverse .lp-it-img { order: 2; }
.lp-it-img img { border-radius: var(--lp-radius); width: 100%; aspect-ratio: 4/3; object-fit: cover; }
.lp-it-title { font-size: 22px; font-weight: 800; margin-bottom: 14px; }
.lp-it-body { font-size: 15px; color: var(--lp-muted); margin-bottom: 18px; }

/* ============ ステップ ============ */
.lp-step-list { counter-reset: step; max-width: 760px; margin: 0 auto; }
.lp-step {
  display: flex; gap: 20px; align-items: flex-start; padding: 22px 0;
  border-bottom: 1px dashed var(--lp-line);
}
.lp-step:last-child { border-bottom: none; }
.lp-step-num {
  flex-shrink: 0; width: 52px; height: 52px; border-radius: 50%;
  background: var(--lp-primary); color: #fff; font-size: 20px; font-weight: 800;
  display: flex; align-items: center; justify-content: center;
}
.lp-step-title { font-size: 18px; font-weight: 700; margin-bottom: 4px; }
.lp-step-desc { font-size: 14px; color: var(--lp-muted); }

/* ============ 比較表 ============ */
.lp-table-wrap { overflow-x: auto; }
.lp-cmp-table { width: 100%; border-collapse: collapse; background: #fff; border-radius: var(--lp-radius); overflow: hidden; }
.lp-cmp-table th, .lp-cmp-table td { padding: 16px 14px; text-align: center; border-bottom: 1px solid var(--lp-line); font-size: 15px; }
.lp-cmp-table thead th { background: var(--lp-soft); font-weight: 700; font-size: 15px; }
.lp-cmp-table .lp-cmp-label { text-align: left; font-weight: 600; background: #fafaf8; }
.lp-cmp-table .lp-cmp-other { color: var(--lp-muted); }
.lp-cmp-table th.lp-cmp-us, .lp-cmp-table td.lp-cmp-us {
  background: color-mix(in srgb, var(--lp-primary) 14%, #fff);
  color: var(--lp-text); font-weight: 700;
}
.lp-cmp-table th.lp-cmp-us { background: var(--lp-primary); color: #fff; }

/* ============ 仕様表 ============ */
.lp-spec-table {
  width: 100%; border-collapse: collapse; background: #fff;
  border: 1px solid var(--lp-line); border-radius: var(--lp-radius); overflow: hidden;
}
.lp-spec-table th, .lp-spec-table td { padding: 14px 18px; border-bottom: 1px solid var(--lp-line); text-align: left; }
.lp-spec-table tr:last-child th, .lp-spec-table tr:last-child td { border-bottom: none; }
.lp-spec-table th { width: 32%; background: #fafaf8; font-weight: 700; white-space: nowrap; }

/* ============ 価格表 ============ */
.lp-plan-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 22px; align-items: stretch; }
.lp-plan {
  position: relative; background: #fff; border: 1px solid var(--lp-line);
  border-radius: var(--lp-radius); padding: 28px 22px; text-align: center;
  display: flex; flex-direction: column;
}
.lp-plan-featured {
  border: 2px solid var(--lp-primary);
  box-shadow: 0 10px 30px color-mix(in srgb, var(--lp-primary) 22%, transparent);
  transform: scale(1.03);
}
.lp-plan-badge {
  position: absolute; top: -12px; left: 50%; transform: translateX(-50%);
  background: var(--lp-accent); color: #2a2200; font-size: 12px; font-weight: 700;
  padding: 4px 16px; border-radius: 20px; white-space: nowrap;
}
.lp-plan-name { font-size: 17px; font-weight: 700; margin-bottom: 10px; }
.lp-plan-price { font-size: 32px; font-weight: 800; color: var(--lp-primary); margin-bottom: 4px; }
.lp-plan-period { font-size: 12px; color: var(--lp-muted); display: block; font-weight: 400; }
.lp-plan-features { list-style: none; padding: 0; margin: 16px 0 20px; text-align: left; flex: 1; }
.lp-plan-features li { padding: 6px 0 6px 26px; position: relative; font-size: 14px; border-bottom: 1px dashed var(--lp-line); }
.lp-plan-features li:last-child { border-bottom: none; }
.lp-plan-features li::before { content: '✓'; position: absolute; left: 4px; color: var(--lp-primary); font-weight: 800; }
.lp-pricing-note { text-align: center; font-size: 13px; color: var(--lp-muted); margin-top: 22px; }

/* ============ ギャラリー ============ */
.lp-gallery-grid { display: grid; gap: 14px; }
.lp-gal-2 { grid-template-columns: repeat(2, 1fr); }
.lp-gal-3 { grid-template-columns: repeat(3, 1fr); }
.lp-gal-4 { grid-template-columns: repeat(4, 1fr); }
.lp-gallery-item { margin: 0; }
.lp-gallery-item img { border-radius: var(--lp-radius); aspect-ratio: 1/1; object-fit: cover; }
.lp-gallery-item figcaption { font-size: 12px; color: var(--lp-muted); margin-top: 6px; text-align: center; }

/* ============ お客様の声 ============ */
.lp-reviews-avg { margin: 8px 0 28px; display: flex; flex-direction: column; align-items: center; gap: 4px; }
.lp-reviews-avg-num { font-size: 40px; font-weight: 800; color: var(--lp-accent); line-height: 1; }
.lp-reviews-avg-stars { color: var(--lp-accent); font-size: 20px; letter-spacing: 2px; }
.lp-reviews-avg-label { font-size: 13px; color: var(--lp-muted); }
.lp-review-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 22px; }
.lp-review {
  background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius);
  padding: 22px;
}
.lp-review-stars { color: var(--lp-accent); font-size: 18px; letter-spacing: 2px; margin-bottom: 8px; }
.lp-review-title { font-weight: 700; margin-bottom: 6px; }
.lp-review-body { font-size: 14px; color: var(--lp-muted); margin-bottom: 12px; }
.lp-review-meta { font-size: 12px; color: var(--lp-muted); }

/* ============ FAQ ============ */
.lp-faq-list { max-width: 760px; margin: 0 auto; }
.lp-faq-item {
  border: 1px solid var(--lp-line); border-radius: var(--lp-radius);
  margin-bottom: 10px; background: #fff; overflow: hidden;
}
.lp-faq-q {
  cursor: pointer; padding: 16px 18px; font-weight: 700; list-style: none;
  display: flex; gap: 8px; align-items: baseline; font-size: 15px;
  position: relative;
}
.lp-faq-q::-webkit-details-marker { display: none; }
.lp-faq-q::after { content: '+'; margin-left: auto; color: var(--lp-primary); font-size: 22px; font-weight: 400; transition: transform .2s; }
.lp-faq-item[open] .lp-faq-q::after { transform: rotate(45deg); }
.lp-faq-mark { color: var(--lp-primary); font-weight: 800; flex-shrink: 0; }
.lp-faq-mark-a { color: var(--lp-accent); }
.lp-faq-a { padding: 0 18px 18px 50px; font-size: 14px; color: var(--lp-muted); }

/* ============ 動画 ============ */
.lp-video-frame { position: relative; width: 100%; aspect-ratio: 16/9; border-radius: var(--lp-radius); overflow: hidden; background: #000; }
.lp-video-frame iframe, .lp-video-frame video { position: absolute; inset: 0; width: 100%; height: 100%; border: 0; }

/* ============ カウントダウン ============ */
.lp-countdown { background: linear-gradient(135deg, var(--lp-primary), color-mix(in srgb, var(--lp-primary) 60%, #000)); color: #fff; padding: 56px 0; }
.lp-countdown .lp-eyebrow { background: rgba(255,255,255,.2); color: #fff; }
.lp-countdown .lp-h2 { color: #fff; }
.lp-cd { display: flex; justify-content: center; gap: 12px; margin: 0 0 28px; flex-wrap: wrap; }
.lp-cd-unit {
  background: rgba(255,255,255,.15); backdrop-filter: blur(6px);
  border-radius: var(--lp-radius); padding: 16px 10px; min-width: 80px; text-align: center;
}
.lp-cd-num { display: block; font-size: clamp(28px, 5vw, 40px); font-weight: 800; line-height: 1; }
.lp-cd-lbl { font-size: 12px; opacity: .9; }

/* ============ CTA ============ */
.lp-cta { padding: 64px 0; }
.lp-cta-title { font-size: clamp(24px, 4.5vw, 34px); font-weight: 800; margin-bottom: 14px; line-height: 1.4; }
.lp-cta-sub { font-size: 16px; opacity: .95; margin-bottom: 26px; }
.lp-cta-btn { margin-bottom: 12px; }
.lp-cta-note { font-size: 13px; opacity: .9; }

/* ============ フッター ============ */
.lp-footer { background: var(--lp-soft); padding: 40px 0; font-size: 13px; color: var(--lp-muted); }
.lp-foot-shop { font-size: 18px; font-weight: 700; color: var(--lp-text); margin-bottom: 16px; }
.lp-foot-links { margin-bottom: 18px; display: flex; flex-wrap: wrap; gap: 6px 4px; }
.lp-foot-links a { color: var(--lp-text); }
.lp-foot-links a:hover { text-decoration: underline; }
.lp-foot-sep { color: var(--lp-muted); margin: 0 4px; }
.lp-foot-info { line-height: 2; margin-bottom: 16px; }
.lp-foot-copy { padding-top: 16px; border-top: 1px solid var(--lp-line); font-size: 12px; }

/* =========================================================
   バリアント別スタイル（各モジュールの2-3種類目以降）
   ========================================================= */

/* --- お知らせバー: マーキー / バナー --- */
.lp-notice-marquee { overflow: hidden; padding: 0; }
.lp-notice-marquee a { display: block; padding: 10px 0; }
.lp-notice-marquee-track { display: inline-block; white-space: nowrap; animation: lp-marquee 18s linear infinite; padding-left: 100%; }
.lp-notice-marquee .nt-sep { margin: 0 14px; opacity: .6; }
@keyframes lp-marquee { 0% { transform: translateX(0); } 100% { transform: translateX(-100%); } }
.lp-notice-banner { border-radius: 0; }
.lp-notice-banner a, .lp-notice-banner > span { display: flex; align-items: center; justify-content: center; gap: 12px; }
.lp-notice-banner .nt-btn {
  background: rgba(255,255,255,.22); padding: 4px 14px; border-radius: 20px; font-size: 12px;
}

/* --- ヒーロー: 分割 / 中央 --- */
.lp-hero-split { padding: 0; min-height: auto; }
.lp-hero-split-row { display: grid; grid-template-columns: 1fr 1fr; align-items: center; min-height: 480px; }
.lp-hero-split-img img { width: 100%; height: 100%; min-height: 480px; object-fit: cover; }
.lp-hero-split-text { padding: 40px; }
.lp-hero-split .lp-hero-title { font-size: clamp(24px, 3.4vw, 36px); text-shadow: none; }
.lp-hero-center { padding: 80px 0; }
.lp-hero-title-center { font-size: clamp(26px, 4.5vw, 40px); }

/* --- リード文: 左寄せ / 引用 --- */
.lp-lead-left .lp-lead-left-eyebrow { font-size: 13px; font-weight: 700; color: var(--lp-primary); letter-spacing: .08em; margin-bottom: 8px; }
.lp-lead-left .lp-lead-left-title { font-size: clamp(22px, 3.6vw, 30px); font-weight: 800; border-left: 4px solid var(--lp-primary); padding-left: 16px; margin-bottom: 20px; line-height: 1.4; }
.lp-lead-left .lp-lead-body { font-size: 16px; }
.lp-lead-quote { padding: 56px 0; }
.lp-quote { font-size: clamp(20px, 3vw, 28px); font-weight: 700; line-height: 1.6; margin: 0 0 16px; color: var(--lp-text); quotes: none; }
.lp-quote::before { content: '\\201C'; font-size: 1.4em; color: var(--lp-primary); line-height: 0; vertical-align: -.3em; margin-right: 4px; }
.lp-quote::after { content: '\\201D'; font-size: 1.4em; color: var(--lp-primary); line-height: 0; vertical-align: -.3em; margin-left: 2px; }
.lp-quote-cite { font-style: normal; font-size: 14px; color: var(--lp-muted); }

/* --- メリット: カード / 番号付き --- */
.lp-feature-grid-card { gap: 22px; }
.lp-feature-card { background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,.04); }
.lp-feature-card-img img { width: 100%; aspect-ratio: 3/2; object-fit: cover; }
.lp-feature-card-body { padding: 18px; }
.lp-feature-card-body .lp-feature-title { font-size: 17px; }
.lp-feature-num-list { display: flex; flex-direction: column; gap: 20px; }
.lp-feature-num { display: flex; gap: 18px; align-items: flex-start; background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); padding: 22px; }
.lp-feature-num-n { flex-shrink: 0; width: 44px; height: 44px; border-radius: 50%; background: var(--lp-primary); color: #fff; font-size: 20px; font-weight: 800; display: flex; align-items: center; justify-content: center; }

/* --- 画像＋文章: 重ね合わせ / カード --- */
.lp-it-overlap { position: relative; margin-bottom: 56px; }
.lp-it-overlap-img img { width: 100%; aspect-ratio: 2/1; object-fit: cover; border-radius: var(--lp-radius); }
.lp-it-overlap-card { background: #fff; margin: -40px auto 0; max-width: 80%; position: relative; padding: 24px; border-radius: var(--lp-radius); box-shadow: 0 8px 24px rgba(0,0,0,.08); border: 1px solid var(--lp-line); }
.lp-it-card-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 22px; }
.lp-it-card { background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,.04); }
.lp-it-card-img img { width: 100%; aspect-ratio: 4/3; object-fit: cover; }
.lp-it-card-body { padding: 18px; }

/* --- ステップ: 矢印 / タイムライン --- */
.lp-step-arrow-list { display: flex; gap: 16px; flex-wrap: wrap; justify-content: center; }
.lp-step-arrow { position: relative; background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); padding: 22px 18px; flex: 1; min-width: 180px; text-align: center; }
.lp-step-arrow-n { font-size: 12px; font-weight: 700; color: var(--lp-primary); letter-spacing: .08em; margin-bottom: 8px; }
.lp-step-arrow-title { font-size: 17px; font-weight: 700; margin-bottom: 6px; }
.lp-step-arrow-mark { display: none; }
@media (min-width: 768px) {
  .lp-step-arrow-mark { display: block; position: absolute; right: -22px; top: 50%; transform: translateY(-50%); color: var(--lp-primary); font-size: 22px; z-index: 1; font-weight: 700; }
}
.lp-step-tl-list { position: relative; padding-left: 32px; }
.lp-step-tl-list::before { content: ''; position: absolute; left: 11px; top: 8px; bottom: 8px; width: 2px; background: var(--lp-line); }
.lp-step-tl { position: relative; padding-bottom: 28px; }
.lp-step-tl-dot { position: absolute; left: -28px; top: 4px; width: 14px; height: 14px; border-radius: 50%; background: var(--lp-primary); border: 3px solid #fff; box-shadow: 0 0 0 2px var(--lp-primary); }
.lp-step-tl-n { font-size: 12px; font-weight: 700; color: var(--lp-primary); letter-spacing: .08em; }
.lp-step-tl-body .lp-step-title { font-size: 17px; margin: 4px 0; }

/* --- 比較表: チェックバツ / カード --- */
.lp-compare-check .lp-ico { display: inline-flex; width: 26px; height: 26px; border-radius: 50%; align-items: center; justify-content: center; font-weight: 800; font-size: 15px; }
.lp-ico-ok { background: var(--lp-primary); color: #fff; }
.lp-ico-ng { background: #d8dadf; color: #8a8580; }
.lp-ico-tri { background: var(--lp-accent); color: #2a2200; }
.lp-cmp-cards { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; align-items: start; }
.lp-cmp-card { position: relative; background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); padding: 24px; }
.lp-cmp-card-us { border: 2px solid var(--lp-primary); box-shadow: 0 8px 24px color-mix(in srgb, var(--lp-primary) 18%, transparent); }
.lp-cmp-card-badge { position: absolute; top: -12px; left: 50%; transform: translateX(-50%); background: var(--lp-accent); color: #2a2200; font-size: 12px; font-weight: 700; padding: 4px 14px; border-radius: 20px; white-space: nowrap; }
.lp-cmp-card-name { font-size: 18px; font-weight: 700; margin-bottom: 14px; text-align: center; }
.lp-cmp-card ul { list-style: none; padding: 0; margin: 0; }
.lp-cmp-card li { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px dashed var(--lp-line); font-size: 14px; }
.lp-cmp-card li:last-child { border-bottom: none; }
.lp-cmp-card-k { color: var(--lp-muted); }
.lp-cmp-card-v { font-weight: 700; }

/* --- 仕様表: 枠囲み / 2カラム --- */
.lp-spec-bd { margin: 0; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); overflow: hidden; }
.lp-spec-bd-row { display: flex; border-bottom: 1px solid var(--lp-line); }
.lp-spec-bd-row:last-child { border-bottom: none; }
.lp-spec-bd dt { width: 35%; background: #fafaf8; padding: 14px 18px; font-weight: 700; }
.lp-spec-bd dd { flex: 1; padding: 14px 18px; margin: 0; }
.lp-spec-2c-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }
.lp-spec-2c-item { background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); padding: 16px; }
.lp-spec-2c-k { font-size: 12px; color: var(--lp-muted); margin-bottom: 4px; }
.lp-spec-2c-v { font-size: 17px; font-weight: 700; }

/* --- 価格表: リスト型 / 強調1プラン --- */
.lp-pricing-list .lp-plan-row-list { display: flex; flex-direction: column; gap: 14px; }
.lp-plan-row { display: flex; justify-content: space-between; align-items: center; gap: 20px; background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); padding: 20px 24px; }
.lp-plan-row-featured { border: 2px solid var(--lp-primary); }
.lp-plan-row-info { flex: 1; }
.lp-plan-row-info .lp-plan-features { margin: 8px 0 0; }
.lp-plan-row-price { text-align: right; }
.lp-plan-row-price .lp-plan-price { font-size: 26px; }
.lp-pricing-single .lp-plan-single { display: grid; grid-template-columns: 1.4fr 1fr; gap: 32px; align-items: center; background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); padding: 32px; box-shadow: 0 8px 24px rgba(0,0,0,.05); }
.lp-pricing-single .lp-plan-old { text-decoration: line-through; color: var(--lp-muted); font-size: 18px; font-weight: 400; margin-right: 10px; }
.lp-pricing-single .lp-plan-price { font-size: 38px; }
.lp-plan-features-2col { display: grid; grid-template-columns: 1fr 1fr; gap: 4px 16px; }
.lp-plan-single-cta { text-align: center; }
.lp-plan-single-cta .lp-btn { display: block; width: 100%; }

/* --- ギャラリー: モザイク / 横スクロール --- */
.lp-gallery-mosaic { display: grid; grid-template-columns: repeat(4, 1fr); grid-auto-rows: 160px; gap: 10px; }
.lp-gallery-mos-item { margin: 0; overflow: hidden; border-radius: var(--lp-radius); position: relative; }
.lp-gallery-mos-item img { width: 100%; height: 100%; object-fit: cover; }
.lp-gallery-mos-item figcaption { position: absolute; bottom: 0; left: 0; right: 0; background: linear-gradient(transparent, rgba(0,0,0,.6)); color: #fff; font-size: 12px; padding: 16px 10px 8px; }
.lp-gal-mos-1 { grid-column: span 2; grid-row: span 2; }
.lp-gal-mos-4 { grid-column: span 2; }
.lp-gallery-scroll { display: flex; gap: 14px; overflow-x: auto; padding-bottom: 12px; scroll-snap-type: x mandatory; }
.lp-gallery-scroll-item { margin: 0; flex-shrink: 0; width: 280px; scroll-snap-align: start; }
.lp-gallery-scroll-item img { width: 280px; height: 280px; object-fit: cover; border-radius: var(--lp-radius); }
.lp-gallery-scroll-item figcaption { font-size: 12px; color: var(--lp-muted); margin-top: 6px; }
.lp-gallery-scroll-hint { text-align: center; font-size: 12px; color: var(--lp-muted); margin-top: 8px; }

/* --- 口コミ: 1件大きく / 平均+引用 --- */
.lp-review-big-card { display: flex; gap: 24px; align-items: center; background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); padding: 28px; box-shadow: 0 4px 16px rgba(0,0,0,.04); }
.lp-review-big-img { flex-shrink: 0; }
.lp-review-big-img img { width: 120px; height: 120px; border-radius: 50%; object-fit: cover; }
.lp-review-big-body { flex: 1; }
.lp-review-big-text { font-size: 18px; font-weight: 600; line-height: 1.6; margin: 8px 0; }
.lp-reviews-avg-hero { display: flex; align-items: center; justify-content: center; gap: 20px; margin-bottom: 32px; }
.lp-reviews-avg-big { font-size: 56px; font-weight: 800; color: var(--lp-accent); line-height: 1; }
.lp-reviews-avg .lp-reviews-avg-stars { font-size: 22px; }
.lp-review-quote-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 18px; }
.lp-review-quote { margin: 0; background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); padding: 18px; }
.lp-review-quote blockquote { margin: 0 0 8px; font-size: 14px; font-weight: 600; line-height: 1.5; }
.lp-review-quote blockquote::before { content: '\\201C'; color: var(--lp-primary); font-weight: 800; }
.lp-review-quote blockquote::after { content: '\\201D'; color: var(--lp-primary); font-weight: 800; }
.lp-review-quote figcaption { font-size: 12px; color: var(--lp-muted); }

/* --- FAQ: 2カラム / 展開リスト --- */
.lp-faq-2c-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; }
.lp-faq-2c-item { background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); padding: 18px; }
.lp-faq-2c-q { font-weight: 700; margin-bottom: 8px; font-size: 15px; }
.lp-faq-2c-a { font-size: 14px; color: var(--lp-muted); }
.lp-faq-list2 .lp-faq-q { padding: 18px 20px; background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); margin-bottom: 8px; }
.lp-faq-list2 .lp-faq-q span { flex: 1; font-weight: 700; }
.lp-faq-list2 .lp-faq-q::after { content: ''; width: 12px; height: 12px; border-right: 3px solid var(--lp-primary); border-bottom: 3px solid var(--lp-primary); transform: rotate(45deg); transition: transform .2s; margin-top: 4px; }
.lp-faq-list2[open] .lp-faq-q::after, .lp-faq-list2.lp-faq-item[open] .lp-faq-q::after { transform: rotate(-135deg); margin-top: 8px; }
.lp-faq-list2 .lp-faq-a { padding: 0 20px 18px; }

/* --- 動画: 正方形 / 全幅 --- */
.lp-video-sq { aspect-ratio: 1/1; max-width: 480px; margin: 0 auto; }
.lp-video-square-sec .lp-container { max-width: 600px; }
.lp-video-full { border-radius: 0; aspect-ratio: 21/9; }
.lp-video-full-sec .lp-video-frame { border-radius: 0; }

/* --- カウントダウン: バー型 / 円形 --- */
.lp-countdown-bar { padding: 0; }
.lp-cd-bar-inner { display: flex; align-items: center; gap: 20px; padding: 16px 0; flex-wrap: wrap; }
.lp-cd-bar-eb { font-size: 12px; font-weight: 700; background: rgba(255,255,255,.2); padding: 4px 10px; border-radius: 20px; }
.lp-cd-bar-title { font-weight: 700; font-size: 16px; }
.lp-cd-bar-time { font-size: 22px; font-weight: 800; font-variant-numeric: tabular-nums; margin-left: auto; }
.lp-countdown-circles .lp-cd-circles { gap: 16px; }
.lp-cd-circle { width: 96px; height: 96px; border-radius: 50%; background: rgba(255,255,255,.15); display: flex; flex-direction: column; align-items: center; justify-content: center; border: 2px solid rgba(255,255,255,.3); }
.lp-cd-circle .lp-cd-num { font-size: 28px; }
.lp-cd-circle .lp-cd-lbl { font-size: 10px; letter-spacing: .1em; opacity: .85; }

/* --- CTA: カード / 分割 --- */
.lp-cta-card-sec { padding: 56px 0; }
.lp-cta-card { background: #fff; border-radius: var(--lp-radius); padding: 40px; text-align: center; box-shadow: 0 8px 30px rgba(0,0,0,.08); border: 1px solid var(--lp-line); }
.lp-cta-card .lp-cta-title, .lp-cta-card .lp-cta-sub, .lp-cta-card .lp-cta-note { color: var(--lp-text); }
.lp-cta-split { padding: 0; }
.lp-cta-split-row { display: grid; grid-template-columns: 1fr 1fr; align-items: center; min-height: 420px; }
.lp-cta-split-text { padding: 48px; }
.lp-cta-split-img img { width: 100%; height: 100%; min-height: 420px; object-fit: cover; }

/* --- フッター: 4カラム / ミニマル --- */
.lp-footer-cols { padding: 56px 0; }
.lp-foot-cols { display: grid; grid-template-columns: 2fr 1fr 1fr 1fr; gap: 32px; margin-bottom: 32px; }
.lp-foot-desc { font-size: 13px; color: var(--lp-muted); margin-top: 12px; line-height: 1.7; }
.lp-foot-col h4 { font-size: 13px; font-weight: 700; margin: 0 0 12px; color: var(--lp-text); }
.lp-foot-col ul { list-style: none; padding: 0; margin: 0; }
.lp-foot-col li { margin-bottom: 8px; }
.lp-foot-col a { color: var(--lp-muted); font-size: 13px; }
.lp-foot-col a:hover { color: var(--lp-primary); }
.lp-footer-minimal { padding: 32px 0; text-align: center; }
.lp-footer-minimal .lp-foot-shop { font-size: 16px; margin-bottom: 12px; }
.lp-footer-minimal .lp-foot-links { justify-content: center; margin-bottom: 12px; }

/* =========================================================
   第4バリアント（レイアウト大幅変更）
   ========================================================= */

/* --- お知らせ: スライダー --- */
.lp-notice-slider { padding: 0; overflow: hidden; position: relative; }
.lp-nt-slider-track { position: relative; height: 40px; }
.lp-nt-slide { position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; opacity: 0; transition: opacity .5s; font-size: 13px; font-weight: 600; }
.lp-nt-slide.active { opacity: 1; }
.lp-notice-slider a { color: inherit; }

/* --- ヒーロー: 動画背景風 --- */
.lp-hero-cinematic { background-size: cover; background-position: center; color: #fff; display: flex; align-items: center; text-align: center; }
.lp-hero-cinematic-inner { width: 100%; }
.lp-hero-cine-eb { background: rgba(255,255,255,.2); color: #fff; }
.lp-hero-play {
  width: 88px; height: 88px; border-radius: 50%; background: rgba(255,255,255,.95); border: none;
  display: inline-flex; align-items: center; justify-content: center; cursor: pointer; margin: 20px 0 8px;
  box-shadow: 0 0 0 0 rgba(255,255,255,.5); animation: lp-pulse 2s infinite; transition: transform .2s;
}
.lp-hero-play:hover { transform: scale(1.08); }
.lp-hero-play-icon { font-size: 28px; color: var(--lp-text); padding-left: 4px; }
.lp-hero-play-label { font-size: 14px; opacity: .9; margin-bottom: 16px; }
.lp-hero-play-cta { color: #fff; text-decoration: underline; font-size: 13px; }
@keyframes lp-pulse { 0% { box-shadow: 0 0 0 0 rgba(255,255,255,.5); } 70% { box-shadow: 0 0 0 20px rgba(255,255,255,0); } 100% { box-shadow: 0 0 0 0 rgba(255,255,255,0); } }

/* --- リード: 数字強調 --- */
.lp-lead-stats { padding: 64px 0; }
.lp-stat-eb { background: rgba(255,255,255,.2); color: inherit; }
.lp-stat-title { color: inherit; }
.lp-stat-grid { display: flex; justify-content: center; gap: 48px; flex-wrap: wrap; margin-top: 28px; }
.lp-stat-num { font-size: clamp(36px, 6vw, 56px); font-weight: 800; color: var(--lp-accent); line-height: 1; }
.lp-stat-label { font-size: 14px; opacity: .9; margin-top: 8px; }

/* --- メリット: 横スクロール --- */
.lp-feature-scroll { display: flex; gap: 16px; overflow-x: auto; padding-bottom: 12px; scroll-snap-type: x mandatory; }
.lp-feature-scroll-card { flex-shrink: 0; width: 240px; background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); padding: 24px; text-align: center; scroll-snap-align: start; box-shadow: 0 2px 10px rgba(0,0,0,.04); }
.lp-feature-scroll-icon { font-size: 40px; margin-bottom: 12px; }
.lp-feature-scroll-hint { text-align: center; font-size: 12px; color: var(--lp-muted); margin-top: 8px; }

/* --- 画像+文章: ジグザグ非対称（マガジン風） --- */
.lp-it-mag-sec { padding: 56px 0; }
.lp-it-mag { display: grid; grid-template-columns: 1fr 1fr; gap: 40px; align-items: center; margin-bottom: 56px; }
.lp-it-mag-offset .lp-it-mag-img { order: 2; }
.lp-it-mag-img img { width: 100%; aspect-ratio: 4/5; object-fit: cover; border-radius: var(--lp-radius); }
.lp-it-mag-kicker { display: inline-block; font-size: 12px; font-weight: 700; color: var(--lp-primary); letter-spacing: .1em; margin-bottom: 8px; }
.lp-it-mag-title { font-size: clamp(20px, 2.6vw, 26px); font-weight: 800; line-height: 1.4; margin-bottom: 12px; }

/* --- ステップ: 大数字カード --- */
.lp-step-bignum-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 24px; }
.lp-step-bignum { background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); padding: 28px 20px; text-align: center; }
.lp-step-bignum-n { font-size: 56px; font-weight: 800; color: var(--lp-primary); line-height: 1; opacity: .3; margin-bottom: 8px; }
.lp-step-bignum-title { font-size: 18px; font-weight: 700; margin-bottom: 6px; }

/* --- 比較表: VS対戦型 --- */
.lp-compare-vs .lp-cmp-vs-headers { display: grid; grid-template-columns: 1fr 1fr; gap: 0; margin-bottom: 0; }
.lp-compare-vs .lp-cmp-vs-h-other, .lp-compare-vs .lp-cmp-vs-h-us { padding: 20px; text-align: center; font-weight: 700; font-size: 18px; }
.lp-compare-vs .lp-cmp-vs-h-other { background: var(--lp-soft); border-radius: var(--lp-radius) 0 0 0; }
.lp-compare-vs .lp-cmp-vs-h-us { background: var(--lp-primary); color: #fff; border-radius: 0 var(--lp-radius) 0 0; }
.lp-cmp-vs-emoji { font-size: 28px; display: block; margin-bottom: 4px; }
.lp-compare-vs .lp-cmp-vs-rows { border: 1px solid var(--lp-line); border-top: none; border-radius: 0 0 var(--lp-radius) var(--lp-radius); overflow: hidden; }
.lp-cmp-vs-row { display: grid; grid-template-columns: 1fr 1fr; gap: 0; border-bottom: 1px solid var(--lp-line); }
.lp-cmp-vs-row:last-child { border-bottom: none; }
.lp-cmp-vs-other, .lp-cmp-vs-us { padding: 14px; text-align: center; font-size: 15px; }
.lp-cmp-vs-us { font-weight: 700; background: color-mix(in srgb, var(--lp-primary) 8%, #fff); }

/* --- 仕様: アイコングリッド --- */
.lp-spec-ic-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 18px; }
.lp-spec-ic { background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); padding: 24px 16px; text-align: center; }
.lp-spec-ic-icon { font-size: 36px; margin-bottom: 8px; }
.lp-spec-ic-label { font-size: 12px; color: var(--lp-muted); margin-bottom: 4px; }
.lp-spec-ic-value { font-size: 16px; font-weight: 700; }

/* --- 価格: トグル切替 --- */
.lp-pricing-toggle .lp-plan-toggle-card { background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); padding: 36px; text-align: center; box-shadow: 0 4px 16px rgba(0,0,0,.04); }
.lp-plan-toggle-switch { position: relative; display: inline-flex; background: var(--lp-soft); border-radius: 30px; padding: 4px; margin-bottom: 20px; }
.lp-plan-toggle-switch input { display: none; }
.lp-toggle-opt span { display: block; padding: 8px 24px; font-size: 14px; font-weight: 600; cursor: pointer; border-radius: 24px; position: relative; z-index: 1; color: var(--lp-muted); transition: color .2s; }
.lp-toggle-opt input:checked + span { color: #fff; }
.lp-toggle-slider { position: absolute; top: 4px; left: 4px; width: calc(50% - 4px); height: calc(100% - 8px); background: var(--lp-primary); border-radius: 24px; transition: transform .25s; }
.lp-plan-toggle-prices { position: relative; min-height: 64px; margin-bottom: 16px; }
.lp-plan-toggle-price { font-size: 36px; font-weight: 800; color: var(--lp-primary); }
.lp-plan-toggle-price small { display: block; font-size: 12px; font-weight: 400; color: var(--lp-muted); }
.lp-plan-toggle-regular { display: block; }
.lp-plan-toggle-single { display: none; }

/* --- ギャラリー: ビフォーアフター --- */
.lp-gallery-ba .lp-ba { position: relative; width: 100%; aspect-ratio: 16/10; border-radius: var(--lp-radius); overflow: hidden; }
.lp-ba-img { position: absolute; inset: 0; }
.lp-ba-img img { width: 100%; height: 100%; object-fit: cover; }
.lp-ba-before { clip-path: polygon(0 0, 50% 0, 50% 100%, 0 100%); }
.lp-ba-tag { position: absolute; top: 12px; padding: 4px 12px; background: rgba(0,0,0,.6); color: #fff; font-size: 12px; border-radius: 20px; }
.lp-ba-after .lp-ba-tag { left: 12px; }
.lp-ba-before .lp-ba-tag { right: 12px; }
.lp-ba-handle { position: absolute; left: 50%; top: 0; bottom: 0; width: 3px; background: #fff; transform: translateX(-50%); }
.lp-ba-handle span { position: absolute; top: 50%; left: 50%; transform: translate(-50%,-50%); width: 40px; height: 40px; background: #fff; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 16px; box-shadow: 0 2px 8px rgba(0,0,0,.3); }
.lp-ba-caption { text-align: center; font-size: 13px; color: var(--lp-muted); margin-top: 12px; }

/* --- 口コミ: 画像付きカード --- */
.lp-reviews-photo .lp-review-photo-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 22px; }
.lp-review-photo { background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); overflow: hidden; }
.lp-review-photo-img img { width: 100%; aspect-ratio: 4/3; object-fit: cover; }
.lp-review-photo-body { padding: 18px; }
.lp-review-photo-body .lp-review-stars { font-size: 16px; margin-bottom: 6px; }

/* --- FAQ: 検索+カテゴリ --- */
.lp-faq-search-sec .lp-faq-search-box { position: relative; max-width: 480px; margin: 0 auto 20px; }
.lp-faq-search-input { width: 100%; padding: 12px 44px 12px 16px; border: 1px solid var(--lp-line); border-radius: var(--lp-radius); font-size: 15px; font-family: inherit; }
.lp-faq-search-box { font-size: 18px; }
.lp-faq-search-box::after { content: '🔍'; position: absolute; right: 16px; top: 50%; transform: translateY(-50%); pointer-events: none; }
.lp-faq-cats { display: flex; gap: 8px; justify-content: center; flex-wrap: wrap; margin-bottom: 24px; }
.lp-faq-cat-btn { padding: 6px 16px; background: transparent; border: 1px solid var(--lp-line); border-radius: 20px; font-size: 13px; cursor: pointer; color: var(--lp-muted); }
.lp-faq-cat-btn.active { background: var(--lp-primary); border-color: var(--lp-primary); color: #fff; }

/* --- 動画: 説明付き --- */
.lp-video-explain .lp-video-explain-row { display: grid; grid-template-columns: 1.6fr 1fr; gap: 24px; align-items: start; }
.lp-video-explain-title { font-size: 16px; font-weight: 700; margin-bottom: 12px; }
.lp-video-explain-points ul { list-style: none; padding: 0; margin: 0; }
.lp-video-point { display: flex; gap: 12px; padding: 10px 0; border-bottom: 1px dashed var(--lp-line); }
.lp-video-point-time { flex-shrink: 0; font-weight: 700; color: var(--lp-primary); font-variant-numeric: tabular-nums; }
.lp-video-point-content { font-size: 14px; }

/* --- カウントダウン: 緊急感（大型） --- */
.lp-countdown-urgent { padding: 80px 0; }
.lp-cd-urgent-eb { background: rgba(255,255,255,.2); color: #fff; animation: lp-blink 1.2s infinite; }
@keyframes lp-blink { 50% { opacity: .5; } }
.lp-cd-urgent-title { color: #fff; }
.lp-cd-urgent { font-variant-numeric: tabular-nums; margin: 16px 0 28px; }
.lp-cd-urgent-num { font-size: clamp(56px, 12vw, 120px); font-weight: 800; line-height: 1; color: #fff; }
.lp-cd-urgent-colon { font-size: clamp(40px, 8vw, 80px); font-weight: 800; color: rgba(255,255,255,.4); margin: 0 4px; vertical-align: top; }
.lp-cd-urgent-btn { animation: lp-blink 1.5s infinite; }

/* --- CTA: スティッキー（追従） --- */
.lp-cta-sticky { padding: 0; position: sticky; bottom: 0; z-index: 50; box-shadow: 0 -4px 20px rgba(0,0,0,.15); }
.lp-cta-sticky-inner { display: flex; align-items: center; justify-content: space-between; gap: 16px; padding: 14px 0; flex-wrap: wrap; }
.lp-cta-sticky-text { display: flex; align-items: center; gap: 16px; flex-wrap: wrap; }
.lp-cta-sticky-title { font-weight: 700; font-size: 15px; }
.lp-cta-sticky-price { font-size: 22px; font-weight: 800; }
.lp-cta-sticky-old { font-size: 14px; text-decoration: line-through; opacity: .7; font-weight: 400; margin-right: 8px; }
.lp-cta-sticky-price small { font-size: 11px; font-weight: 400; }
.lp-cta-sticky-btn { white-space: nowrap; }

/* --- フッター: ニュースレター --- */
.lp-footer-newsletter { padding: 56px 0; }
.lp-nl-hero { text-align: center; max-width: 560px; margin: 0 auto 32px; }
.lp-nl-shop { font-size: 18px; font-weight: 700; margin-bottom: 16px; }
.lp-nl-title { font-size: clamp(20px, 3vw, 26px); font-weight: 800; margin-bottom: 12px; }
.lp-nl-sub { font-size: 14px; opacity: .9; margin-bottom: 20px; }
.lp-nl-form { display: flex; gap: 8px; max-width: 420px; margin: 0 auto 8px; }
.lp-nl-input { flex: 1; padding: 12px 16px; border: none; border-radius: var(--lp-radius); font-size: 15px; font-family: inherit; }
.lp-nl-note { font-size: 12px; opacity: .7; }
.lp-nl-links { justify-content: center; margin-bottom: 16px; }

/* =========================================================
   レスポンシブ
   ========================================================= */
@media (max-width: 900px) {
  .lp-root > section { padding: 44px 0; }
  .lp-feature-grid { grid-template-columns: 1fr; gap: 16px; }
  .lp-it-row { grid-template-columns: 1fr; gap: 18px; margin-bottom: 40px; }
  .lp-it-reverse .lp-it-img { order: 0; }
  .lp-review-grid { grid-template-columns: 1fr; }
  .lp-plan-grid { grid-template-columns: 1fr; gap: 18px; }
  .lp-plan-featured { transform: none; }
  .lp-gal-4 { grid-template-columns: repeat(2, 1fr); }
  .lp-gal-3 { grid-template-columns: repeat(2, 1fr); }
  .lp-hero { min-height: auto !important; padding: 56px 0; }
  .lp-hero-inner { max-width: 100%; }
  .lp-cmp-table th, .lp-cmp-table td { padding: 12px 8px; font-size: 13px; }
  /* バリアント別 SP対応 */
  .lp-hero-split-row { grid-template-columns: 1fr; }
  .lp-hero-split-img img { min-height: 280px; }
  .lp-hero-split-text { padding: 32px 20px; }
  .lp-it-card-grid { grid-template-columns: 1fr; }
  .lp-cmp-cards { grid-template-columns: 1fr; }
  .lp-spec-2c-grid { grid-template-columns: 1fr; }
  .lp-plan-row { flex-direction: column; align-items: flex-start; }
  .lp-plan-row-price { text-align: left; width: 100%; }
  .lp-pricing-single .lp-plan-single { grid-template-columns: 1fr; }
  .lp-plan-features-2col { grid-template-columns: 1fr; }
  .lp-review-big-card { flex-direction: column; text-align: center; }
  .lp-review-quote-grid { grid-template-columns: 1fr; }
  .lp-faq-2c-grid { grid-template-columns: 1fr; }
  .lp-cta-split-row { grid-template-columns: 1fr; }
  .lp-cta-split-text { padding: 40px 20px; }
  .lp-cta-split-img img { min-height: 280px; }
  .lp-foot-cols { grid-template-columns: 1fr 1fr; gap: 24px; }
  .lp-gallery-mosaic { grid-template-columns: repeat(2, 1fr); grid-auto-rows: 140px; }
  .lp-gal-mos-1 { grid-column: span 2; grid-row: span 1; }
  .lp-step-arrow-list { flex-direction: column; }
  /* 第4バリアント SP対応 */
  .lp-stat-grid { gap: 28px; }
  .lp-it-mag { grid-template-columns: 1fr; gap: 20px; margin-bottom: 40px; }
  .lp-it-mag-offset .lp-it-mag-img { order: 0; }
  .lp-step-bignum-grid { grid-template-columns: 1fr; }
  .lp-compare-vs .lp-cmp-vs-headers { grid-template-columns: 1fr; }
  .lp-compare-vs .lp-cmp-vs-h-other { border-radius: var(--lp-radius) var(--lp-radius) 0 0; }
  .lp-compare-vs .lp-cmp-vs-h-us { border-radius: 0; }
  .lp-cmp-vs-row { grid-template-columns: 1fr; }
  .lp-cmp-vs-other { border-bottom: 1px solid var(--lp-line); }
  .lp-spec-ic-grid { grid-template-columns: 1fr 1fr; }
  .lp-review-photo-grid { grid-template-columns: 1fr; }
  .lp-video-explain-row { grid-template-columns: 1fr; }
  .lp-cta-sticky-inner { flex-direction: column; gap: 10px; text-align: center; }
  .lp-cta-sticky-text { flex-direction: column; gap: 6px; }
  .lp-cta-sticky-btn { width: 100%; }
}
@media (max-width: 480px) {
  .lp-root { font-size: 14px; }
  .lp-gal-4, .lp-gal-3, .lp-gal-2 { grid-template-columns: 1fr; }
  .lp-btn { padding: 13px 22px; font-size: 15px; }
  .lp-btn-lg { padding: 16px 28px; font-size: 16px; }
  .lp-cd-unit { min-width: 64px; padding: 12px 6px; }
  .lp-spec-table th { width: 38%; }
}

/* 編集モード専用: モジュール選択ハイライト（エディタ iframe 内で有効化） */
.lp-root.lp-editing .lp-block {
  position: relative; cursor: pointer; outline: 2px solid transparent; outline-offset: -2px;
  transition: outline-color .12s;
}
.lp-root.lp-editing .lp-block:hover { outline-color: rgba(91,140,255,.5); }
.lp-root.lp-editing .lp-block.lp-selected { outline-color: #5b8cff; }
`;
})();
