/* AUTO-GENERATED by build-styles.js — 編集は css/preview.css を行い再生成してください */
(function () {
  'use strict';
  const LP = (window.LP = window.LP || {});
  // LP 本体CSS文字列（プレビュー/エクスポートで共用）
  LP.LP_CSS = `/* =========================================================
   preview.css — LP 本体スタイル（エディタプレビュー ＆ エクスポートHTML で共用）
   テーマ色は CSS 変数で注入:
   --lp-primary --lp-accent --lp-bg --lp-text --lp-radius --lp-font
   ========================================================= */

.lp-root {
  /* デフォルト（上書き前提） */
  --lp-primary: #e87a8b;
  --lp-accent: #f6c453;
  --lp-bg: #ffffff;
  --lp-text: #2d2a26;
  --lp-radius: 12px;
  --lp-font: 'Hiragino Sans','Hiragino Kaku Gothic ProN','Noto Sans JP',sans-serif;
  --lp-muted: #8a8580;
  --lp-line: #eceae6;
  --lp-soft: #f6f4f0;
}

.lp-root, .lp-root * {
  box-sizing: border-box;
}
.lp-root {
  font-family: var(--lp-font);
  color: var(--lp-text);
  background: var(--lp-bg);
  line-height: 1.75;
  font-size: 15px;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  margin: 0;
}
.lp-root p, .lp-root h1, .lp-root h2, .lp-root h3, .lp-root ul, .lp-root figure { margin: 0; }
.lp-root img { max-width: 100%; height: auto; display: block; }
.lp-root a { color: var(--lp-primary); text-decoration: none; }

/* レイアウト コンテナ */
.lp-container { max-width: 1120px; margin: 0 auto; padding: 0 20px; }
.lp-narrow { max-width: 820px; }
.lp-center { text-align: center; }

/* セクション間隔 */
.lp-root > section { padding: 56px 0; }

/* 見出し */
.lp-eyebrow {
  display: inline-block; font-size: 13px; font-weight: 700;
  letter-spacing: .14em; color: var(--lp-primary);
  background: color-mix(in srgb, var(--lp-primary) 12%, transparent);
  padding: 4px 14px; border-radius: 30px; margin-bottom: 16px;
}
.lp-h2 {
  font-size: clamp(22px, 4vw, 32px); font-weight: 800; line-height: 1.4;
  margin-bottom: 28px;
}
.lp-section-head { margin-bottom: 36px; }
.lp-section-head.lp-center .lp-h2 { margin-bottom: 16px; }

/* ボタン */
.lp-btn {
  display: inline-block; padding: 14px 32px; border-radius: var(--lp-radius);
  font-weight: 700; font-size: 16px; cursor: pointer; border: 2px solid transparent;
  transition: transform .15s ease, box-shadow .15s ease, opacity .15s;
  text-align: center; line-height: 1.3;
}
.lp-btn:hover { transform: translateY(-2px); }
.lp-btn:active { transform: translateY(0); }
.lp-btn-primary { background: var(--lp-primary); color: #fff; box-shadow: 0 6px 18px color-mix(in srgb, var(--lp-primary) 40%, transparent); }
.lp-btn-outline { background: transparent; border-color: var(--lp-primary); color: var(--lp-primary); }
.lp-btn-white { background: #fff; color: var(--lp-text); box-shadow: 0 6px 18px rgba(0,0,0,.18); }
.lp-btn-lg { padding: 18px 44px; font-size: 18px; }
.lp-btn-block { display: block; width: 100%; }

/* ============ お知らせバー ============ */
.lp-notice {
  padding: 10px 16px; text-align: center; font-size: 13px; font-weight: 600;
  letter-spacing: .02em;
}
.lp-notice a { color: inherit; display: block; }
.lp-notice .nt-link { margin-left: 8px; opacity: .9; }

/* ============ ヒーロー ============ */
.lp-hero {
  background-size: cover; background-position: center; color: #fff;
  display: flex; align-items: center; padding: 60px 0;
}
.lp-hero-inner { max-width: 720px; }
.lp-align-center { margin-left: auto; margin-right: auto; }
.lp-align-right { margin-left: auto; }
.lp-hero .lp-eyebrow { background: rgba(255,255,255,.2); color: #fff; }
.lp-hero-title {
  font-size: clamp(28px, 5.5vw, 46px); font-weight: 800; line-height: 1.35;
  margin: 6px 0 18px; text-shadow: 0 2px 12px rgba(0,0,0,.25);
}
.lp-hero-sub { font-size: clamp(15px, 2.2vw, 18px); margin-bottom: 28px; opacity: .98; }
.lp-hero-cta { margin-bottom: 12px; }
.lp-hero-note { font-size: 13px; opacity: .92; }

/* ============ リード文 ============ */
.lp-lead { padding: 64px 0; }
.lp-lead .lp-h2 { margin-bottom: 22px; }
.lp-lead-body { font-size: 16px; max-width: 680px; margin: 0 auto; }

/* ============ 3つのメリット ============ */
.lp-feature-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 24px; }
.lp-feature {
  background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius);
  padding: 28px 22px; text-align: center;
  box-shadow: 0 2px 8px rgba(0,0,0,.03);
}
.lp-feature-icon { font-size: 42px; line-height: 1; margin-bottom: 12px; }
.lp-feature-title { font-size: 18px; font-weight: 700; margin-bottom: 8px; }
.lp-feature-desc { font-size: 14px; color: var(--lp-muted); }

/* ============ 画像＋文章 ============ */
.lp-it-row {
  display: grid; grid-template-columns: 1fr 1fr; gap: 36px; align-items: center;
  margin-bottom: 56px;
}
.lp-it-row:last-child { margin-bottom: 0; }
.lp-it-reverse .lp-it-img { order: 2; }
.lp-it-img img { border-radius: var(--lp-radius); width: 100%; aspect-ratio: 4/3; object-fit: cover; }
.lp-it-title { font-size: 22px; font-weight: 800; margin-bottom: 14px; }
.lp-it-body { font-size: 15px; color: var(--lp-muted); margin-bottom: 18px; }

/* ============ ステップ ============ */
.lp-step-list { counter-reset: step; max-width: 760px; margin: 0 auto; }
.lp-step {
  display: flex; gap: 20px; align-items: flex-start; padding: 22px 0;
  border-bottom: 1px dashed var(--lp-line);
}
.lp-step:last-child { border-bottom: none; }
.lp-step-num {
  flex-shrink: 0; width: 52px; height: 52px; border-radius: 50%;
  background: var(--lp-primary); color: #fff; font-size: 20px; font-weight: 800;
  display: flex; align-items: center; justify-content: center;
}
.lp-step-title { font-size: 18px; font-weight: 700; margin-bottom: 4px; }
.lp-step-desc { font-size: 14px; color: var(--lp-muted); }

/* ============ 比較表 ============ */
.lp-table-wrap { overflow-x: auto; }
.lp-cmp-table { width: 100%; border-collapse: collapse; background: #fff; border-radius: var(--lp-radius); overflow: hidden; }
.lp-cmp-table th, .lp-cmp-table td { padding: 16px 14px; text-align: center; border-bottom: 1px solid var(--lp-line); font-size: 15px; }
.lp-cmp-table thead th { background: var(--lp-soft); font-weight: 700; font-size: 15px; }
.lp-cmp-table .lp-cmp-label { text-align: left; font-weight: 600; background: #fafaf8; }
.lp-cmp-table .lp-cmp-other { color: var(--lp-muted); }
.lp-cmp-table th.lp-cmp-us, .lp-cmp-table td.lp-cmp-us {
  background: color-mix(in srgb, var(--lp-primary) 14%, #fff);
  color: var(--lp-text); font-weight: 700;
}
.lp-cmp-table th.lp-cmp-us { background: var(--lp-primary); color: #fff; }

/* ============ 仕様表 ============ */
.lp-spec-table {
  width: 100%; border-collapse: collapse; background: #fff;
  border: 1px solid var(--lp-line); border-radius: var(--lp-radius); overflow: hidden;
}
.lp-spec-table th, .lp-spec-table td { padding: 14px 18px; border-bottom: 1px solid var(--lp-line); text-align: left; }
.lp-spec-table tr:last-child th, .lp-spec-table tr:last-child td { border-bottom: none; }
.lp-spec-table th { width: 32%; background: #fafaf8; font-weight: 700; white-space: nowrap; }

/* ============ 価格表 ============ */
.lp-plan-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 22px; align-items: stretch; }
.lp-plan {
  position: relative; background: #fff; border: 1px solid var(--lp-line);
  border-radius: var(--lp-radius); padding: 28px 22px; text-align: center;
  display: flex; flex-direction: column;
}
.lp-plan-featured {
  border: 2px solid var(--lp-primary);
  box-shadow: 0 10px 30px color-mix(in srgb, var(--lp-primary) 22%, transparent);
  transform: scale(1.03);
}
.lp-plan-badge {
  position: absolute; top: -12px; left: 50%; transform: translateX(-50%);
  background: var(--lp-accent); color: #2a2200; font-size: 12px; font-weight: 700;
  padding: 4px 16px; border-radius: 20px; white-space: nowrap;
}
.lp-plan-name { font-size: 17px; font-weight: 700; margin-bottom: 10px; }
.lp-plan-price { font-size: 32px; font-weight: 800; color: var(--lp-primary); margin-bottom: 4px; }
.lp-plan-period { font-size: 12px; color: var(--lp-muted); display: block; font-weight: 400; }
.lp-plan-features { list-style: none; padding: 0; margin: 16px 0 20px; text-align: left; flex: 1; }
.lp-plan-features li { padding: 6px 0 6px 26px; position: relative; font-size: 14px; border-bottom: 1px dashed var(--lp-line); }
.lp-plan-features li:last-child { border-bottom: none; }
.lp-plan-features li::before { content: '✓'; position: absolute; left: 4px; color: var(--lp-primary); font-weight: 800; }
.lp-pricing-note { text-align: center; font-size: 13px; color: var(--lp-muted); margin-top: 22px; }

/* ============ ギャラリー ============ */
.lp-gallery-grid { display: grid; gap: 14px; }
.lp-gal-2 { grid-template-columns: repeat(2, 1fr); }
.lp-gal-3 { grid-template-columns: repeat(3, 1fr); }
.lp-gal-4 { grid-template-columns: repeat(4, 1fr); }
.lp-gallery-item { margin: 0; }
.lp-gallery-item img { border-radius: var(--lp-radius); aspect-ratio: 1/1; object-fit: cover; }
.lp-gallery-item figcaption { font-size: 12px; color: var(--lp-muted); margin-top: 6px; text-align: center; }

/* ============ お客様の声 ============ */
.lp-reviews-avg { margin: 8px 0 28px; display: flex; flex-direction: column; align-items: center; gap: 4px; }
.lp-reviews-avg-num { font-size: 40px; font-weight: 800; color: var(--lp-accent); line-height: 1; }
.lp-reviews-avg-stars { color: var(--lp-accent); font-size: 20px; letter-spacing: 2px; }
.lp-reviews-avg-label { font-size: 13px; color: var(--lp-muted); }
.lp-review-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 22px; }
.lp-review {
  background: #fff; border: 1px solid var(--lp-line); border-radius: var(--lp-radius);
  padding: 22px;
}
.lp-review-stars { color: var(--lp-accent); font-size: 18px; letter-spacing: 2px; margin-bottom: 8px; }
.lp-review-title { font-weight: 700; margin-bottom: 6px; }
.lp-review-body { font-size: 14px; color: var(--lp-muted); margin-bottom: 12px; }
.lp-review-meta { font-size: 12px; color: var(--lp-muted); }

/* ============ FAQ ============ */
.lp-faq-list { max-width: 760px; margin: 0 auto; }
.lp-faq-item {
  border: 1px solid var(--lp-line); border-radius: var(--lp-radius);
  margin-bottom: 10px; background: #fff; overflow: hidden;
}
.lp-faq-q {
  cursor: pointer; padding: 16px 18px; font-weight: 700; list-style: none;
  display: flex; gap: 8px; align-items: baseline; font-size: 15px;
  position: relative;
}
.lp-faq-q::-webkit-details-marker { display: none; }
.lp-faq-q::after { content: '+'; margin-left: auto; color: var(--lp-primary); font-size: 22px; font-weight: 400; transition: transform .2s; }
.lp-faq-item[open] .lp-faq-q::after { transform: rotate(45deg); }
.lp-faq-mark { color: var(--lp-primary); font-weight: 800; flex-shrink: 0; }
.lp-faq-mark-a { color: var(--lp-accent); }
.lp-faq-a { padding: 0 18px 18px 50px; font-size: 14px; color: var(--lp-muted); }

/* ============ 動画 ============ */
.lp-video-frame { position: relative; width: 100%; aspect-ratio: 16/9; border-radius: var(--lp-radius); overflow: hidden; background: #000; }
.lp-video-frame iframe, .lp-video-frame video { position: absolute; inset: 0; width: 100%; height: 100%; border: 0; }

/* ============ カウントダウン ============ */
.lp-countdown { background: linear-gradient(135deg, var(--lp-primary), color-mix(in srgb, var(--lp-primary) 60%, #000)); color: #fff; padding: 56px 0; }
.lp-countdown .lp-eyebrow { background: rgba(255,255,255,.2); color: #fff; }
.lp-countdown .lp-h2 { color: #fff; }
.lp-cd { display: flex; justify-content: center; gap: 12px; margin: 0 0 28px; flex-wrap: wrap; }
.lp-cd-unit {
  background: rgba(255,255,255,.15); backdrop-filter: blur(6px);
  border-radius: var(--lp-radius); padding: 16px 10px; min-width: 80px; text-align: center;
}
.lp-cd-num { display: block; font-size: clamp(28px, 5vw, 40px); font-weight: 800; line-height: 1; }
.lp-cd-lbl { font-size: 12px; opacity: .9; }

/* ============ CTA ============ */
.lp-cta { padding: 64px 0; }
.lp-cta-title { font-size: clamp(24px, 4.5vw, 34px); font-weight: 800; margin-bottom: 14px; line-height: 1.4; }
.lp-cta-sub { font-size: 16px; opacity: .95; margin-bottom: 26px; }
.lp-cta-btn { margin-bottom: 12px; }
.lp-cta-note { font-size: 13px; opacity: .9; }

/* ============ フッター ============ */
.lp-footer { background: var(--lp-soft); padding: 40px 0; font-size: 13px; color: var(--lp-muted); }
.lp-foot-shop { font-size: 18px; font-weight: 700; color: var(--lp-text); margin-bottom: 16px; }
.lp-foot-links { margin-bottom: 18px; display: flex; flex-wrap: wrap; gap: 6px 4px; }
.lp-foot-links a { color: var(--lp-text); }
.lp-foot-links a:hover { text-decoration: underline; }
.lp-foot-sep { color: var(--lp-muted); margin: 0 4px; }
.lp-foot-info { line-height: 2; margin-bottom: 16px; }
.lp-foot-copy { padding-top: 16px; border-top: 1px solid var(--lp-line); font-size: 12px; }

/* =========================================================
   レスポンシブ
   ========================================================= */
@media (max-width: 900px) {
  .lp-root > section { padding: 44px 0; }
  .lp-feature-grid { grid-template-columns: 1fr; gap: 16px; }
  .lp-it-row { grid-template-columns: 1fr; gap: 18px; margin-bottom: 40px; }
  .lp-it-reverse .lp-it-img { order: 0; }
  .lp-review-grid { grid-template-columns: 1fr; }
  .lp-plan-grid { grid-template-columns: 1fr; gap: 18px; }
  .lp-plan-featured { transform: none; }
  .lp-gal-4 { grid-template-columns: repeat(2, 1fr); }
  .lp-gal-3 { grid-template-columns: repeat(2, 1fr); }
  .lp-hero { min-height: auto !important; padding: 56px 0; }
  .lp-hero-inner { max-width: 100%; }
  .lp-cmp-table th, .lp-cmp-table td { padding: 12px 8px; font-size: 13px; }
}
@media (max-width: 480px) {
  .lp-root { font-size: 14px; }
  .lp-gal-4, .lp-gal-3, .lp-gal-2 { grid-template-columns: 1fr; }
  .lp-btn { padding: 13px 22px; font-size: 15px; }
  .lp-btn-lg { padding: 16px 28px; font-size: 16px; }
  .lp-cd-unit { min-width: 64px; padding: 12px 6px; }
  .lp-spec-table th { width: 38%; }
}

/* 編集モード専用: モジュール選択ハイライト（エディタ iframe 内で有効化） */
.lp-root.lp-editing .lp-block {
  position: relative; cursor: pointer; outline: 2px solid transparent; outline-offset: -2px;
  transition: outline-color .12s;
}
.lp-root.lp-editing .lp-block:hover { outline-color: rgba(91,140,255,.5); }
.lp-root.lp-editing .lp-block.lp-selected { outline-color: #5b8cff; }
`;
})();
