/* build-styles.js — css/preview.css から js/lp-styles.js を生成
 *   実行: node build-styles.js
 *   これにより LP 本体CSSが文字列として JS に埋め込まれ、
 *   プレビュー iframe / エクスポート HTML が file:// でも動く。
 */
const fs = require('fs');
const path = require('path');

const cssPath = path.join(__dirname, 'css', 'preview.css');
const outPath = path.join(__dirname, 'js', 'lp-styles.js');

const css = fs.readFileSync(cssPath, 'utf8');
// テンプレートリテラル内で壊れる文字をエスケープ
const escaped = css
  .replace(/\\/g, '\\\\')   // バックスラッシュ
  .replace(/`/g, '\\`')      // バックティック
  .replace(/\$\{/g, '\\${'); // ${ を \${ に

const out =
  '/* AUTO-GENERATED by build-styles.js — 編集は css/preview.css を行い再生成してください */\n' +
  '(function () {\n' +
  "  'use strict';\n" +
  '  const LP = (window.LP = window.LP || {});\n' +
  '  // LP 本体CSS文字列（プレビュー/エクスポートで共用）\n' +
  '  LP.LP_CSS = `' + escaped + '`;\n' +
  '})();\n';

fs.writeFileSync(outPath, out, 'utf8');
console.log('Generated ' + outPath + ' (' + out.length + ' bytes) from ' + cssPath);
